// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://emkrjgwmuxwuoavxhehb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVta3JqZ3dtdXh3dW9hdnhoZWhiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM5ODE2NzEsImV4cCI6MjA2OTU1NzY3MX0.bM98AI9LPQkIotZkC7sfo6FojaZm_UHx4uX0FKVbOfQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});